###
POST http://localhost:8080/v1/customers
Content-Type: application/json

{
  "name": "{{$random.name.name}}",
  "email": "{{$random.email}}"
}

###
PATCH http://localhost:8080/v1/customers/19fef767-23df-4ce6-83a8-f3b42782a0aa/activate

###
POST http://localhost:8080/v1/customers/19fef767-23df-4ce6-83a8-f3b42782a0aa/products
Content-Type: application/json

{
  "productName": "Rustic Marble Keyboard"
}

###
GET http://localhost:8080/v1/customers/19fef767-23df-4ce6-83a8-f3b42782a0aa/subscriptions?status=ACTIVE