###
POST http://localhost:8080/v1/customers
Content-Type: application/json

{
  "name": "{{$random.name.name}}",
  "email": "{{$random.email}}"
}

###
PATCH http://localhost:8080/v1/customers/300d5d28-0411-4eef-b24c-824911fd9f9d/activate

###
POST http://localhost:8080/v1/customers/300d5d28-0411-4eef-b24c-824911fd9f9d/products
Content-Type: application/json

{
  "productName": "Practical Aluminum Shirt"
}

###
GET http://localhost:8080/v1/customers/300d5d28-0411-4eef-b24c-824911fd9f9d/subscriptions?status=REQUESTED